"""change kb and document ids to string

Revision ID: d55da58278e9
Revises: 41c5c62e094c
Create Date: 2026-02-01 20:41:09.206061+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d55da58278e9"
down_revision: Union[str, None] = "41c5c62e094c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Removed drop_table for better-auth tables (user, session, account, verification)
    # Those tables are managed by better-auth, not alembic

    # Drop foreign key constraints first (before changing column types)
    op.drop_constraint("documents_uploaded_by_id_fkey", "documents", type_="foreignkey")
    op.drop_constraint("knowledge_bases_owner_id_fkey", "knowledge_bases", type_="foreignkey")
    op.drop_constraint("knowledge_bases_tenant_id_fkey", "knowledge_bases", type_="foreignkey")

    # Change column types from UUID to String
    op.alter_column(
        "documents",
        "uploaded_by_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_bases",
        "tenant_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_bases",
        "owner_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Removed recreation of better-auth tables (user, session, account, verification)
    # Those tables are managed by better-auth, not alembic

    # Change column types back from String to UUID
    op.alter_column(
        "knowledge_bases",
        "owner_id",
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    op.alter_column(
        "knowledge_bases",
        "tenant_id",
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column(
        "documents",
        "uploaded_by_id",
        existing_type=sa.String(length=255),
        type_=sa.UUID(),
        existing_nullable=False,
    )

    # Recreate foreign key constraints
    op.create_foreign_key(
        "knowledge_bases_tenant_id_fkey", "knowledge_bases", "tenants", ["tenant_id"], ["id"]
    )
    op.create_foreign_key(
        "knowledge_bases_owner_id_fkey", "knowledge_bases", "users", ["owner_id"], ["id"]
    )
    op.create_foreign_key(
        "documents_uploaded_by_id_fkey", "documents", "users", ["uploaded_by_id"], ["id"]
    )
    # ### end Alembic commands ###
